spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autotil?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          scope:
            - repo
            - read:user
            - user:email
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true